[package]
name = "storage"
version = "0.1.0"
edition = "2024"

[dependencies]
serde_json = {workspace = true}
async-trait = {workspace = true}
thiserror = {workspace = true}

[dev-dependencies]
tokio= {workspace = true}
